##
# Exercise 1
#
# @file
# @version 0.1

FILES=(exercise1 exercise2 exercise3 exercise4)
C_FILES=exercise1.c exercise2.c exercise3.c exercise4.c
CC=gcc
WARN=-Wall -Wextra -pedantic
EX_3_WARN=-O3 -Wall
make:
	$(CC) $(WARN) exercise1.c -o exercise1.o
	$(CC) $(WARN) exercise2.c -o exercise2.o
	$(CC) $(EX_3_WARN) exercise3.c -o exercise3.o
	$(CC) $(WARN) exercise4.c -o exercise4.o
# end
